#! /bin/sh

top_padding_size=45
if command -v xrandr > /dev/null 2>&1; then
	height=$(xrandr | grep '*' | awk '{print $1}' | cut -d'x' -f2)
	if [ -n "$height" ]; then
		top_padding_size=$(awk "BEGIN { printf \"%d\", $height * 0.03 }")
	fi
fi

setxkbmap -layout us
# custom keymap
#[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

pgrep -x sxhkd > /dev/null || sxhkd &
feh --randomize --bg-fill ~/.Pictures/wallhaven-2yxp16.jpg
pgrep -x polybar > /dev/null || ~/.config/polybar/launch.sh &
pgrep -x picom > /dev/null || picom &
#pgrep -x fcitx5 > /dev/null || fcitx5 &
# pgrep autokey >/dev/null || autokey &
#pgrep -x fcitx > /dev/null || fcitx &
pgrep -x ibus-daemon > /dev/null || ibus-daemon -rxR &

#pgrep -x clash > /dev/null || /opt/clash/clash &
vmware-user-suid-wrapper

bspc monitor -d I II III IV V VI

bspc config border_width 3
#bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
#bspc config gapless_monocle false
bspc config window_gap 0
bspc config top_padding "$top_padding_size"
bspc config bottom_padding 20
bspc config left_padding 10
bspc config right_padding 10
bspc config single_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# for dacs
# open dacs te as float window at screen center
# bspc rule -a dacs_desk_clerk state=floating center=on focus=on layer=above border=off rectangle=1376x860+0+0
bspc rule -a dacs_desk_clerk state=floating center=on focus=on layer=above border=off desktop=VI
bspc rule -a eudic state=floating center=on focus=on layer=above border=on rectangle=800x500+0+0
