[helpers]

[default]
depends = []

[default.files]
vimrc = "~/.vimrc"
"wezterm.lua" = { target = "~/.config/wezterm/wezterm.lua", type = "template" }

[default.variables]

[windows]
[windows.files]
"change.ahk" = "~/.config/autohotkey/change.ahk"
"Microsoft.PowerShell_profile.ps1"="~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[ubuntu]
[ubuntu.files]
polybar = { target="~/.config/polybar", type="symbolic" }
bspwm = "~/.config/bspwm"
sxhkd = "~/.config/sxhkd"
rofi = "~/.config/rofi"
Xmodmap = "~/.Xmodmap"
Xresources = { target = "~/.Xresources", type = "template" }

[ubuntu.variables]
dpi="108"
