[helpers]

[default]
depends = []

[default.files]
vimrc = "~/.vimrc"
"wezterm.lua" = { target = "~/.config/wezterm/wezterm.lua", type = "template" }

[default.variables]

[windows]
[windows.files]
"change.ahk" = "~/.config/autohotkey/change.ahk"
"Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[ubuntu]
[ubuntu.files]
polybar = { target = "~/.config/polybar", type = "symbolic" }
bspwm = "~/.config/bspwm"
sxhkd = "~/.config/sxhkd"
rofi = { target = "~/.config/rofi", type = "symbolic" }
Xmodmap = "~/.Xmodmap"
Xresources = { target = "~/.Xresources", type = "template" }
wallpaper = { target = "~/.Pictures", type = "symbolic" }
"tmux.conf" = { target = "~/.tmux.conf", type = "symbolic" }
"tmux/memory.sh" = { target = "~/.tmux/plugins/tmux/custom/memory.sh", type = "symbolic" }
"tmux/mem_usage.sh" = { target = "~/.tmux/plugins/tmux/custom/mem_usage.sh", type = "symbolic" }
"zsh/zshrc" = { target = "~/.zshrc", type = "template" }
"zsh/supc.zsh-theme" = { target = "~/.oh-my-zsh/custom/themes/supc.zsh-theme", type = "symbolic" }


[ubuntu.variables]
dpi = "108"
username = "supc"
