[helpers]

[default]
depends = []

[default.files]
vimrc = "~/.vimrc"
wezterm = { target = "~/.config/wezterm/wezterm.lua", type = "template" }

[default.variables]
wezterm_opacity = 0.9
wezterm_hide_tab = false
wezterm_font_size = 15
wezterm_rows = 30
wezterm_cols = 120

[windows]
[windows.files]
"change.ahk" = { target = "~/.config/autohotkey/change.ahk", type = "template" }
"Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"yazi/yazi.toml" = {target="~/AppData/Roaming/yazi/config/yazi.toml", type = "template"}

[windows.variables]
ahk_caps_lock = ";"
username = "supengchuan"

[ubuntu]
[ubuntu.files]
bspwm = "~/.config/bspwm"
sxhkd = "~/.config/sxhkd"
rofi = { target = "~/.config/rofi", type = "symbolic" }
Xmodmap = "~/.Xmodmap"
Xresources = { target = "~/.Xresources", type = "template" }
wallpaper = { target = "~/.Pictures", type = "symbolic" }
"tmux.conf" = { target = "~/.tmux.conf", type = "symbolic" }
"tmux/mem_usage.sh" = { target = "~/.config/tmux/custom/mem_usage.sh", type = "symbolic" }
"zsh/zshrc" = { target = "~/.zshrc", type = "template" }
"zsh/supc.zsh-theme" = { target = "~/.oh-my-zsh/custom/themes/supc.zsh-theme", type = "symbolic" }
"xbindkeysrc" = { target = "~/.xbindkeysrc", type = "symbolic" }
"xremap/config.yaml" = { target = "~/.config/xremap/config.yaml", type = "symbolic" }
"xremap/xremap.service" = { target = "~/.config/systemd/user/xremap.service", type = "template" }
lazygit = { target = "~/.config/lazygit/config.yml", type = "symbolic" }
"ranger/rc.conf" = { target = "~/.config/ranger/rc.conf", type = "symbolic" }
"dacs/dacs" = { target = "~/.config/dacs/dacs", type = "symbolic" }
"yazi/yazi.toml" = {target="~/.config/yazi/yazi.toml", type = "symbolic"}

[ubuntu.variables]
dpi = "108"
username = "supc"

[polybar]
[polybar.files]
"polybar/scripts" = { target = "~/.config/polybar/scripts", type = "symbolic" }
"polybar/colors.ini" = { target = "~/.config/polybar/colors.ini", type = "symbolic" }
"polybar/launch.sh" = { target = "~/.config/polybar/launch.sh", type = "symbolic" }
"polybar/modules.ini" = { target = "~/.config/polybar/modules.ini", type = "symbolic" }
"polybar/config.ini" = { target = "~/.config/polybar/config.ini", type = "template" }

[polybar.variables]
polybar_heigth = "2%"
polybar_offset_y = "0.6%"
polybar_font_size = 18
